/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomeHouseV3: typeof import('./src/components/HomeHouse-v3/HomeHouse-v3.vue')['default']
    HomeHouseV9: typeof import('./src/components/HomeHouse-v9/HomeHouse-v9.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/tabbar/index.vue')['default']
    TabbarView: typeof import('./src/components/tabbar/tabbarView.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanIndexAnchor: typeof import('vant/es')['IndexAnchor']
    VanIndexBar: typeof import('vant/es')['IndexBar']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
